### ISSUE TITLE
PHP Fatal error:  Class 'Drupal\serialization\Normalizer\NormalizerBase' during install.php

### ISSUE THREAD

**Issue by rbarreca** [drugan/commerce_multistore#6]
When running through the Drupal install after doing a 

`composer create-project --repository=https://raw.githubusercontent.com/drugan/project-base/8.x/packages.json drugan/project-base drugan --stability dev`

I get a fatal AJAX HTTP error when the commerce_base module is attempting to install.
> Installing Drupal
The installation has encountered an error.
Please continue to the error page

>An AJAX HTTP error occurred.
HTTP Result Code: 500
Debugging information follows.
Path: /core/install.php?rewrite=ok&profile=commerce_base&langcode=en&id=1&op=do_nojs&op=do
StatusText: Internal Server Error
ResponseText: 

`[13-Nov-2017 04:11:26 Europe/Berlin] PHP Fatal error:  Class 'Drupal\serialization\Normalizer\NormalizerBase' not found in /Users/rbarreca/nerd/drugan/web/modules/commerce_core_modules/commerce/modules/order/src/Normalizer/AdjustmentNormalizer.php on line 11`

at http://localhost:8888/core/install.php?rewrite=ok&profile=commerce_base&langcode=en&id=1&op=start

Seems similar to this issue: https://www.drupal.org/node/2899234. Any ideas? Just me?

**Comment by drugan** [comment]
Yes, it was the issue with the commit on the base Drupal Commerce project but now they've reverted changes and I also updated my repository. See more:

https://www.drupal.org/node/2916252#comment-12313416

Please, try now if you can get it installed.

**Comment by rbarreca** [comment]
Thanks, it works now. After running a `composer update`, dropping database, the install.php process complete.
